### ISSUE TITLE
multiple content: for bottom pane

### ISSUE THREAD

**Issue by friendde** [roemhildtg/cmv-widgets#20]
I would like to also use the Advanced Search Widget with your Related Table widget. How do I specify more than one ```content: ```
in the div tag?

``` html
content: '<div id="attributesContainer"></div>','<div id="relatedRecords" style="height:100%;"></div>'

**Comment by roemhildtg** [comment]
@friendde I'm trying to guess what you want to accomplish, do you want to have the Advanced Search Widget as a new tab in the Related Table Widget?

**Comment by friendde** [comment]
I don't think I want a new tab (unless it's necessary). But I do want to be able to configure the app to use both widgets. I am confused on how to configure the bottom pane so both widgets can be used in the application. Basically add your widget. Both widgets require the bottom pane ```content: ```
to be configured.

**Comment by roemhildtg** [comment]
Ah, I see. Try this: 
```javascript
content: '<div id="attributesContainer" style="width:40%;height:100%;"></div>'<div id="relatedRecords" style="height:100%;width:40%;"></div>'
```

You might need to play around with the width/height.

**Comment by roemhildtg** [comment]
Just a side note, they don't necessarily need the bottom pane configured, you can place each widget anywhere in theory, but since the related records widget is quite large, I recommend placing it in a bottom or top pane.

**Comment by friendde** [comment]
Thanks, it places the RelatedRecords Tab underneath the Attributes tab. I am ok with that. Thanks for making this. I have another question but I will ask in the chat at the CMV page.

**Comment by roemhildtg** [comment]
@friendde You might be able to fit them side by side by using `float:left` in the css.
