### ISSUE TITLE
Using fields from a related table in a popup template, that is formatted as an attribute list

### ISSUE THREAD

**Issue by dfralia** [roemhildtg/cmv-widgets#21]
Hi all, 
I am new to using the CMV code, (and JS). I am trying to get related records to show up in an attribute list format. I am able to get the related records table to work properly, however the data shows up in tabs. I don't really want the tabs. I want the data to show up as it does here (with some different formatting though)
![untitled](https://cloud.githubusercontent.com/assets/13559288/13113907/617e1ba4-d54e-11e5-8c25-e7647ee0edee.png)

I can only get the code to show the records from the main feature class, and not from the related table. I am using the code from the CMV documents. I can swap out the "formatters.attributeList" with "formatters.relationship" but that will put the related fields into tabs.

Any help on this is much appreciated!

      `define([
    'dojo/dom-construct',
    'dojo/_base/lang',
    'dijit/layout/TabContainer',
    'dijit/layout/ContentPane',
       // 'widgets/roemhildtg/widgets/RelationshipTable/RelationshipTable'//path is relevent to     wherever you placed the file
    'gis/dijit/RelationshipTable/RelationshipTable'
    ], function (domConstruct, lang, TabContainer, ContentPane, RelationshipTable) {
    var formatters = {
         attributeList: 
        function (identifyInfo) {
        var listItem = '<li>{0}: {1}</li>';
        var html = ['<ul>'];
        for (var a in identifyInfo.attributes) {
            //make sure a is an own property
            if (identifyInfo.attributes.hasOwnProperty(a)) {
                html.push(lang.replace(listItem, [a, identifyInfo.attributes[a]]));
            }
        }
        html.push('</ul>');
        return html.join('');
    },

    relationship: function (relationship) {
       return function (data) {
           var content = new ContentPane({
               style: 'height:300px; width: 100%'

           }, domConstruct.create('div'));
           content.startup();

           content.addChild(new RelationshipTable(lang.mixin({
               attributes: data.attributes,
               title: 'Related Records',
               style: 'width:100%;'
           }, relationship)));
               return content.domNode;
    };
        }
    };
    return {
    map: true,
    mapClickMode: true,
    mapRightClickMenu: true,
    identifyLayerInfos: true,
    identifyTolerance: 5,
    identifies: {
       LandManagement: {
                        2: {
                            title: 'BLM',
                            content: formatters.attributeList`

**Comment by roemhildtg** [comment]
So here's the problem, the relationship table renders itself as a table, not as a list. So in your example above, the popup content would look something like this: 

- ObjectID: 10
- ADMIN_DEPT_CODE: DOI
- ...Other feature class attributes

ID | Related field 2 | Related field 3 | ...
-----| ----- | ---- | ----
1 | Record Value | Record Value | ...
2 | Record Value | Record Value | ...
3 | Record Value | Record Value | ...

Is that what you're going for?

**Comment by dfralia** [comment]
Yes the relationships do end up showing in the table format, however I was wanting them to be in the same format, or similar to the attribute list. 
So, perhaps something like this (or similar): 

- ObjectID: 10

- ADMIN_DEPT_CODE: DOI

- .....ETC

- Related Field 2: (Record 1) , Related Field 3: (Record 2) ---------_Field 2 would be first name, field 3 is last name_

**Comment by roemhildtg** [comment]
That won't be easy to accomplish since the widget uses dgrid and doesn't actually do the table rendering itself. It just queries ArcGIS Server for data and loads it into a store. Dgrid does the rest by generating the rows. I suppose one hackish option would be to use CSS to override the look of the table and make it look like a list. 

But why not just format your attributes into a table, and then have two tables, one for the attributes, one for the related records?

**Comment by dfralia** [comment]
Those are some good ideas. I will see what if I can implement, or perhaps create a new widget somehow. I will post back here for reference if I can get something to work.

Thanks for the help and ideas. Much appreciated!

**Comment by roemhildtg** [comment]
@dfralia did you get this figured out? I just added a complete example to the demo branch of this repo. You can see it here: https://github.com/roemhildtg/cmv-widgets/blob/demo-widgets/cmv-app/js/config/identify.js#L84

**Comment by dfralia** [comment]
I had not been able to figure something else out yet. I actually got pulled into another project, and put this on the backburner for a little bit. I just implemented your new demo, and it looks very good. I think I will be able to work with this.  Thank you for posting it.
