### ISSUE TITLE
Appsetting can't save visible layer

### ISSUE THREAD

**Issue by shshwang** [roemhildtg/cmv-widgets#22]
Hi, I am new to Javascript and CMV. 
Thanks for sharing your code, I am able to add the appsetting widget to save extent but can't display visible layer. 
Below is the error I got when copy the URL to a new browser. 

 TypeError: layer.layer.setVisibleLayers is not a function(…)(anonymous function) @ init.js:31

Any thoughts on what could cause the error?

Thanks,
Shen

**Comment by roemhildtg** [comment]
@shshwang are you able to provide an example of this happening or perhaps the config file that you're using to configure the widget? 

You probably stumbled upon an issue but it's really difficult to provide help without a live example or at least the config you're using. 

To share the config, create a new gist.

**Comment by shshwang** [comment]
Thank you so much for your timely response!
I figured out, it is the tiled layer causing the problem. When I comment
the tiled service out. It works.
I remember someone posted share the basemap, I will try tomorrow. Then
update the post.

Really appreciate for sharing the widget. Saved me lots of time :)

Best,

Shen

**Comment by roemhildtg** [comment]
Ah, yes it may be possible that my widget doesn't account for tiled layers since I've only used dynamic layers as operational layers in cmv. 

This wouldn't be a difficult fix, I'll look into it when I have some free time.

**Comment by roemhildtg** [comment]
@shshwang sorry I put this off so long, I forgot about it. Should be taken care of now.
