### ISSUE TITLE
AppSetting widget in CMV develop version

### ISSUE THREAD

**Issue by ERS-Long** [roemhildtg/cmv-widgets#24]
Hi, @roemhildtg 

Have you tried the appSetting widget in the CMV develop version? It seems to me i cannot click any of the checkbox

![image](https://cloud.githubusercontent.com/assets/5911272/17256275/7030c28c-5582-11e6-94b2-b32bbca07d22.png)

it has no error, but when look more into it, seems in file AppSetting.js

this function is never called

this.loadAppSettings();

Please see if you know some of the hint to resolve this.

Thanks

**Comment by roemhildtg** [comment]
Can you post your config for the app settings widget?

**Comment by ERS-Long** [comment]
Here is the config setting

            shareMap: {
                include: true,
                id: 'shareMap',
                position: 17,
                type: 'titlePane',
                canFloat: false,
                path: 'widgets/AppSettings',
                title: '<i class="icon-large icon-paper-clip"></i>&nbsp;&nbsp;Save/Share Current Map',
                options: {
                    //required:
                     map: true,
                     layerControlLayerInfos: true,

                     //optional (defaults shown): 
                     appSettings: {
                        saveBasemap: {
                            save: true,
                            checkbox: true,
                            value: {},
                            urlLoad: false,
                            label: 'Save Current Basemap'
                        }                                                
                     },
                     parametername: 'cmvSettings',
                     mapRightClickMenu: true,
                     address: 'email@email.com',
                     subject: 'Share Map',
                     body: 'Check out this map! <br /> ',
                     emailSettings: ['saveMapExtent', 'saveLayerVisibility', 'saveBasemap'],
                     shareNode: null,
                     shareTemplate: '<a href="#"><i class="fa fa-fw fa-envelope-o"></i>Share Map</a>',
                     server: './widgets/AppSettings/php/index.php'
                }
            },

**Comment by roemhildtg** [comment]
Okay, so your using the php script. Is there an ajax request occurring in your network log? If so, can you post the parameters/data retrieved from the network request?

**Comment by ERS-Long** [comment]
dont have that info, but i got the following error 

![image](https://cloud.githubusercontent.com/assets/5911272/17300948/47ff3046-57da-11e6-8b56-9fd008be541d.png)

**Comment by ERS-Long** [comment]
when i click the left checkbox, it does do something but the checkbox remains unchecked no matter what.

**Comment by roemhildtg** [comment]
Can you post the stack trace on that Uncaught TypeError also? That would be helpful in diagnosing the issue

**Comment by ERS-Long** [comment]
i dont see that error after i reloaded this viewer, (the viewer is Tim's version with WAB widgets plug in).

**Comment by roemhildtg** [comment]
I'll take a look at that viewer later today and see if I can find out more details. Also just fyi, I updated the demo branch of this repo to use the latest cmv develop branch. https://github.com/roemhildtg/cmv-widgets/tree/demo I didn't see any problems but I didn't test with the php script.

**Comment by ERS-Long** [comment]
yes, using the develop version, i can plug this share widget in, and it seems ok, but the issue is when i tried to open the map using something like url/?cmvSettings=4, it wont show/hide the layer and basemap like before. Please see if you can re-produce this and figure out what i did wrong. Thanks a lot!

**Comment by ERS-Long** [comment]
looks there is some issue with the php, it log some records, but it is kind of empty.

![image](https://cloud.githubusercontent.com/assets/5911272/17303962/cba2b284-57e8-11e6-8766-c297f8282de7.png)

**Comment by roemhildtg** [comment]
Hm, I can't seem to reproduce. I downloaded the wab version that tim had and it doesn't seem to have an issue. I'll try testing some of the other widgets though.

```json
{"mapExtent":{"center":{"type":"point","x":-11488671.598416623,"y":5079434.614815155,"spatialReference":{"wkid":102100,"latestWkid":3857}},"zoom":9},"layerVisibility":{"DamageAssessment":{"visible":false,"visibleLayers":[0]},"timeKansas":{"visible":false,"visibleLayers":[-1]},"Petrolium":{"visible":false},"wellFields":{"visible":false},"my_tiled_layer":{"visible":true,"visibleLayers":[1,2,3,4,6,7,8,9,10,11]}}}
```
![spectacle tj4792](https://cloud.githubusercontent.com/assets/5471079/17310480/5a2457b2-580a-11e6-8a52-200f7bf19f34.png)

**Comment by roemhildtg** [comment]
@ERS-Long did you ever find a solution to this?

**Comment by ERS-Long** [comment]
@roemhildtg I did not get chance to look more into it, if you cannot re-produce it, we can close it for now. I will try to dig into next time. Thanks!
