### ISSUE TITLE
use mediaInfos with relationshiptable values

### ISSUE THREAD

**Issue by jkyoungchoi** [roemhildtg/cmv-widgets#25]
Hi,
I was wondering if you were able to populate chart using mediaInfos? If so, can you share how you did?

Thanks,

C

**Comment by roemhildtg** [comment]
I haven't used charting in a popup. But here's a sample I found: https://developers.arcgis.com/javascript/3/jssamples/popup_chart.html

**Comment by jkyoungchoi** [comment]
Thanks,
So, your relationshiptable widget successfully gets values, thanks a lot, but I couldn't go further yet.
I have another question: I can see results that I need function in _addRecord (in widget) but not sure how I can bring it back to (other tabcontainer, in config identify) parse?
Thanks,

**Comment by roemhildtg** [comment]
So, you want to get the data values in a relationship table and put them somewhere?

**Comment by jkyoungchoi** [comment]
right, basically on my popup there will be two tabs. one is just table and the other one will be chart.
Somehow, trying to make it work, since can't use mediainfo (maybe it works, but couldn't make it work) going to implement https://developers.arcgis.com/javascript/3/jssamples/widget_infowindowchart.html insetead. but still couldn't bring "right" data for it.

**Comment by roemhildtg** [comment]
Ah. I see. Yeah it's a little confusing since when you specify `content:relationshipFunction(..)` it actually **overrides** the entire esri popup. So you lose all the "extra" functionality like media infos, attachements, and other stuff. 

You can add a chart though by creating it manually. Just call your `tabContainer.addChild(new dojox.charting.Chart2D());` Or something to that effect.

**Comment by jkyoungchoi** [comment]
thanks, I didn't think about it.
Gonna try!

**Comment by jkyoungchoi** [comment]
so, finally data comes in
but I couldn't access it via js.
console shows:
key: data
object [] 
 > 0: Object
 > 1: Object
 > 2: Object
    length:3

problem is that object shows empty [] , therefore can't access it.
it should be like: [Object, Object, Object] instead.

Do you have any idea that how I can fix this?

Thanks

**Comment by roemhildtg** [comment]
It would help if you posted what your code looks like, I usually do something like this: 

https://github.com/roemhildtg/cmv-widgets/tree/master/widgets/RelationshipTable#include-in-identify-popup

**Comment by jkyoungchoi** [comment]
here is code:
var formatters = {
        relationship: function (relationship) {
           return function (data) {
               var container = new TabContainer({
                   style: 'width:100%;height:300px;'
               }, domConstruct.create('div'));
               container.startup();
               //delay then resize
               setTimeout(function () {
                   container.resize();
               }, 200);
               	var x = new RelationshipTable(lang.mixin({
               		attributes: data.attributes
               }, relationship));
               	var dddd = x.store;
               	var cccc = dddd.data;
               	console.log(cccc)

**Comment by jkyoungchoi** [comment]
it was loop problem, I was calling it while is not done.

Thanks for help!

**Comment by roemhildtg** [comment]
Ah, so you solved it?

**Comment by jkyoungchoi** [comment]
yeah, just delay a sec and then everything works fine
