### ISSUE TITLE
Related Record issue maybe

### ISSUE THREAD

**Issue by ERS-Long** [roemhildtg/cmv-widgets#27]
Great Widget.

Got one problem here, if i use the widget in the identify manner, it generally works fine, but if my identify return two or more records at one time, then that next button seems does not refresh the data correctly. Please see if you have the same problem or not.

Thanks!

**Comment by roemhildtg** [comment]
@ERS-Long thanks for the report. Can you give a little more detail on what's not refreshing correctly? Also your identify config/formatters code snippet might be helpful.

**Comment by ERS-Long** [comment]
@roemhildtg Thanks for your reply. Here is a screen shot

![image](https://cloud.githubusercontent.com/assets/5911272/20891280/a16cb31c-bacf-11e6-92cb-f45251106c44.png)


The identify tool returned three records because they are very close to each other. If i use the > button on the popup on top, the data pane does not refresh or show the next record.

Here is my config part

        relationships: function (title, relationships) {
            return function (data) {

                var container = new TabContainer({
                    style: 'width:100%;height:360px;'
                }, domConstruct.create('div', {id: "relatedWidgetDiv"}));
                container.startup();
                //delay then resize
                setTimeout(function () {
                    container.resize();
                }, 300);

                var attributesPane = new ContentPane({
                    title: title,
                    content: formatters.attributeList(data)
                });                            
                container.addChild(attributesPane);

                arrayUtil.forEach(relationships, function (relationship) {
                    container.addChild(new RelationshipTable(lang.mixin({
                        attributes: data.attributes,
                        title: 'Related Records',
                        style: 'width:100%;'
                    }, relationship)));                
                }, this);

                return container.domNode;
            };
        },


layer setting part

                1: {
                    title: 'Sites',                    
                    content: formatters.relationships('Sites', 
                    [{
                        title: 'Related FRP_COMPLIANCE',
                        objectIdField: 'OBJECTID',
                        relationshipId: 0,
                        url: 'https://wwwwwwwwww/rest/services/TERA_Internal/TERA_Internal_Facilities/MapServer/1',
                        columns: [{
                                label: 'OBJECTID',
                                field: 'OBJECTID',
                                hidden: true
                            }, {
                                label: 'FRP_ID',
                                field: 'FRP_ID'
                            }, {
                                label: 'FACILITY_ID',
                                field: 'FACILITY_ID',
                                hidden: false
                            }, {
                                label: 'ACTIVITY_TYPE',
                                field: 'ACTIVITY_TYPE'
                            }, {
                                label: 'ACTIVITY_SUB_TYPE',
                                field: 'ACTIVITY_SUB_TYPE'
                            }, {
                                label: 'DATE_COMPLETED',
                                field: 'DATE_COMPLETED',
                                get: function (object) { // allow export as a proper date
                                    return new Date(object.DATE_COMPLETED);
                                },
                                formatter: formatters.formatDateTime
                                //hidden: true
                            }, {
                                label: 'SOURCE',
                                field: 'SOURCE'
                            }]
                    },{
                        title: 'Related FRP_CONTACTS',
                        objectIdField: 'OBJECTID',
                        relationshipId: 1,
                        url: 'https://wwwwwwwwww/rest/services/TERA_Internal/TERA_Internal_Facilities/MapServer/1',
                        columns: [{
                                label: 'OBJECTID',
                                field: 'OBJECTID',
                                hidden: true
                            }, {
                                label: 'FRP_ID',
                                field: 'FRP_ID'
                            }, {
                                label: 'FACILITY_ID',
                                field: 'FACILITY_ID',
                                hidden: false
                            }, {
                                label: 'CONTACT_TYPE',
                                field: 'CONTACT_TYPE'
                            }, {
                                label: 'FIRST_NAME',
                                field: 'FIRST_NAME'
                            }, {
                                label: 'LAST_NAME',
                                field: 'LAST_NAME'
                            }, {
                                label: 'FULL_NAME',
                                field: 'FULL_NAME'
                            }, {
                                label: 'JOB_TITLE',
                                field: 'JOB_TITLE',
                                hidden: true
                            }, {
                                label: 'PHONE_NUMBER',
                                field: 'PHONE_NUMBER',
                                hidden: true
                            }, {
                                label: 'PHONE_24HR_NUMBER',
                                field: 'PHONE_24HR_NUMBER',
                                hidden: true
                            }, {
                                label: 'MOBILE_PHONE_NUMBER',
                                field: 'MOBILE_PHONE_NUMBER',
                                hidden: true
                            }, {
                                label: 'EMAIL',
                                field: 'EMAIL',
                                hidden: true
                            }, {
                                label: 'COMMENTS',
                                field: 'COMMENTS',
                                hidden: true
                            }, {
                                label: 'SOURCE',
                                field: 'SOURCE'
                            }]
                    },{
                        title: 'Related FRP_OSRO',
                        objectIdField: 'OBJECTID',
                        relationshipId: 2,
                        url: 'https://wwwwwwwwwww/rest/services/TERA_Internal/TERA_Internal_Facilities/MapServer/1',
                        columns: [{
                                label: 'OBJECTID',
                                field: 'OBJECTID',
                                hidden: true
                            }, {
                                label: 'FRP_ID',
                                field: 'FRP_ID'
                            }, {
                                label: 'FACILITY_ID',
                                field: 'FACILITY_ID',
                                hidden: false
                            }, {
                                label: 'OSRO_NAME',
                                field: 'OSRO_NAME'
                            }, {
                                label: 'OSRO_CITY',
                                field: 'OSRO_CITY'
                            }, {
                                label: 'OSRO_CLASSIFICATION',
                                field: 'OSRO_CLASSIFICATION'
                            }, {
                                label: 'OSRO_STREET_ADDRESS_1',
                                field: 'OSRO_STREET_ADDRESS_1',
                                hidden: true
                            }, {
                                label: 'OSRO_STREET_ADDRESS_2',
                                field: 'OSRO_STREET_ADDRESS_2',
                                hidden: true
                            }, {
                                label: 'OSRO_STATE',
                                field: 'OSRO_STATE',
                                hidden: true
                            }, {
                                label: 'OSRO_POSTAL_CODE',
                                field: 'OSRO_POSTAL_CODE',
                                hidden: true
                            }, {
                                label: 'SOURCE',
                                field: 'SOURCE'
                            }]
                    }
                    ])                    
                },

**Comment by roemhildtg** [comment]
Hmm, that's odd. I haven't tried putting multiple relationships in a tab but it shouldn't be a problem. Is it throwing any errors when you toggle features?

**Comment by ERS-Long** [comment]
oh, it does throws an error, because i used a named id  div  domConstruct.create('div', {id: "relatedWidgetDiv"}));


I will debug it more. Thanks.

**Comment by ERS-Long** [comment]
Great, that is it!  Thank you so much.

**Comment by roemhildtg** [comment]
10-4. :+1:
