### ISSUE TITLE
Relateion table does not work for dynamic layers

### ISSUE THREAD

**Issue by mtabdar** [roemhildtg/cmv-widgets#30]
Hi
Thanks for the amazing widgets espcially the relation table. It is fantastic but i couldn't use it with my dynamic layers. is it a bug or i am doing something wrong?

**Comment by roemhildtg** [comment]
Nope, its not a bug, its just a limitation of the widget. It uses Feature layer "clicks" to do the query. I do have an example of it working with dynamic layers though, but it works a little differently. It uses the identify popup to display the table instead. Would that meet your needs?

https://github.com/roemhildtg/cmv-widgets/tree/master/widgets/RelationshipTable#include-in-identify-popup

**Comment by mtabdar** [comment]
Thanks. In fact it is exactly what i want but i cannot do it!
I used your samples just changed the urls to my own. Then i set identify to show relation tables it workd fine for "petrolium" (why is it not petroleum?)  which is feature layer but couldndo the same for timekansas which is dynamic. I also changed petroleum to dynamic and the identify stopped showing relation table.!!?

**Comment by roemhildtg** [comment]
Does the identify show up at all? Or are there error messages?

**Comment by mtabdar** [comment]
Yes identify shows regular identify values and no errors just some svg.js errors which are not related to this.

**Comment by roemhildtg** [comment]
Off the top of my head, it sounds llike your layer id might not match up with your identify layer id.

In viewer.js (or main cmv config file), what is:
- `layer.type`
- `layer.options.id`
- `layer.url` (not the fulll url, but whether its `/MapServer/0` or `/Maperver` or `/Mapserver/1` etc

In identify.js config file, what is:
 - the name of your identifies layer
 - the number of your identifies sublayer

**Comment by roemhildtg** [comment]
Similarly, for feature layers, the only thing you'd need to change is this in viewer.js:
```javascript
{
            id: 'assets',
            type: 'feature',
            url: '/arcgis/rest/services/internal/assets/MapServer/25',
            title: 'Assets and Utilities',
            options: {
                outFields: '*',
                id: 'assets'
            },
            layerControlLayerInfos: {
                expanded: true
            }
        },
```

**Comment by mtabdar** [comment]
In viewer.js
Layer type. Dynamic 
Layer options id. timeKansas
layer.url /MapServer/

In identify.js
timeKansas is the layer id
I don't get number of identifies sublayer i add one feature layer with two relation tabels (which work as expecte) and this dynamic layer "timekansa" it has two sub layers.
May i ask what about the url used in parameters of factory. It seems that it is a feature url (with /0 at the end) the same is introduced to identify with layer id and sublayer id

**Comment by mtabdar** [comment]
I'm sorry. I don't get the point of your last comment. Feature layers work fine my problem is with dynamic layers. Thanks

**Comment by mtabdar** [comment]
Yes you are right. When i checked and corrected sublayer id's and relation id's i could see the related records in identify. Thanks.
Though i have 2 problems
1. My layer with id =0 doesn't show the related records
2. Although i have set a 1:M relationship and provided several records in the table for each objectid, only one record is shown as the result.

**Comment by roemhildtg** [comment]
There's a fix for number 1, it is a bug in the identify widget: https://github.com/cmv/cmv-app/pull/706

For number 2, it might be helpful for you to look at the network logs when you do the identify. Then you can see what query is being passed to the server, and what it is returning as a response.

**Comment by mtabdar** [comment]
thanks. 
1- i think you are right about "layer with id =0" because i encountered some other issues with it (label layers for example) but unfortunately i couldn't understand if there is a fix available or the root of the problem is identified and you are trying to fix it?
2- again you are right and i should investigate more about it.
thanks a lot for the help.

**Comment by roemhildtg** [comment]
The problem is identified, but has not been included in cmv-app yet.

**Comment by roemhildtg** [comment]
This fix is now in the cmv develop branch. You should be able to download the latest version and have this issue resolved.
