### ISSUE TITLE
Problem with labellayer

### ISSUE THREAD

**Issue by mtabdar** [roemhildtg/cmv-widgets#31]
Hi. Thank you for this great widget. I would be really greatful if you could help me with this issue, I have added label layer to my app ad it seems to work fine because a new layer is created and added to my layers but it has no label.

**Comment by roemhildtg** [comment]
Thanks for the report. Have you set `showLabels: true` in your [`mapOptions`](https://github.com/roemhildtg/cmv-widgets/blob/gh-pages/js/config/viewer.js#L30)?

**Comment by mtabdar** [comment]
Fantastic!
yes that was the solution. thank you.
