### ISSUE TITLE
Reset timeslider on close

### ISSUE THREAD

**Issue by tr3vorm** [roemhildtg/cmv-widgets#32]
It would be useful to have the timeslider reset the temporal extents when the timeslider widget it is closed so that all data date ranges are shown.

**Comment by roemhildtg** [comment]
This is a good idea. I can add it if I get some time someday. Otherwise pull requests welcome 😀 

Something like this would work:
```javascript
if(this.parentWidget){
    this.own(this.parentWidget.on('show', lang.hitch(this, 'resetTimeslider')));
}
```

**Comment by roemhildtg** [comment]
Just found this example: https://github.com/tmcgee/cmv-widgets/commit/80809d48915c52fc47bbd7a583e8265d64490bc6
