### ISSUE TITLE
Demo branch not available

### ISSUE THREAD

**Issue by bapak71** [roemhildtg/cmv-widgets#35]
Hi, I'm new with all this. I find your widget is interesting to explore but there is not enough sample for me to follow.

I see you mentioned there is a [DEMO BRANCH](https://github.com/roemhildtg/cmv-widgets/tree/demo). Unfortunately i got error 404 when I follow the link.

Help is very much appreciated

Thanks

**Comment by roemhildtg** [comment]
I updated the link in the readme. Thanks for letting me know.
